github.com:
    users:
        DROPTASK:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: DROPTASK
